# Generated by Django 5.0.1 on 2024-02-08 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_rename_productimage_productimagemodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimagemodel",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_images",
                to="products.productmodel",
            ),
        ),
        migrations.CreateModel(
            name="ProductPropertiesModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("length", models.FloatField()),
                ("width", models.FloatField()),
                ("high", models.FloatField()),
                ("weight", models.FloatField()),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="properties",
                        to="products.productmodel",
                    ),
                ),
            ],
        ),
    ]
