# Generated by Django 5.0.1 on 2024-02-08 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_alter_productimagemodel_product_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productpropertiesmodel",
            name="product",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="properties",
                to="products.productmodel",
            ),
        ),
    ]
